In [1]:
import numpy as np
import pandas as pd

In [2]:
temperatures_w1= np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])

In [3]:
print(temperatures_w1.shape)
print(temperatures_w1.dtype)
print(temperatures_w1.size)

(7,)
float64
7


In [4]:
temperatures_fahrenheit= (temperatures_w1*9/5)+ 32
print(temperatures_fahrenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [5]:
print (temperatures_fahrenheit.max())
print (temperatures_fahrenheit.min())
print (temperatures_fahrenheit.mean())

78.98
69.44
74.37714285714286


In [6]:
print (np.round(temperatures_fahrenheit.mean(),2))

74.38


In [7]:
print (temperatures_fahrenheit[0:3])
print (temperatures_fahrenheit[-2:])
print (temperatures_fahrenheit[2:5])

[72.5  77.54 69.44]
[76.64 71.42]
[69.44 74.12 78.98]


In [10]:
temperatures= np.array([
    [22.5,25.3,20.8,23.4,26.1,24.8,21.9],
    [19.2,22.5,21.3,24,23.5,22.8,20.1]
])

In [11]:
print(temperatures.shape)
print(temperatures.dtype)
print(temperatures.size)

(2, 7)
float64
14


In [12]:
print(temperatures[0])
print(temperatures[1])
print(temperatures[:,-2:])

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
[19.2 22.5 21.3 24.  23.5 22.8 20.1]
[[24.8 21.9]
 [22.8 20.1]]


In [15]:
marks= pd.Series([95,92,89,85,80], 
                  index= ['rank1', 'rank2','rank3','rank4','rank5'])
print(marks)

rank1    95
rank2    92
rank3    89
rank4    85
rank5    80
dtype: int64


In [17]:
print(marks.iloc[0])
print(marks.loc['rank1':'rank3'])
print(marks.iloc[2])
print(marks[marks>90])

95
rank1    95
rank2    92
rank3    89
dtype: int64
89
rank1    95
rank2    92
dtype: int64


In [18]:
marks['rank1']= 100
marks= marks.drop('rank5')
print(marks)


rank1    100
rank2     92
rank3     89
rank4     85
dtype: int64


In [19]:
cgpa= marks/100
print(cgpa)

rank1    1.00
rank2    0.92
rank3    0.89
rank4    0.85
dtype: float64


In [23]:
transactions= pd.DataFrame({
    'Transaction_ID':[101,102,103,104,105,106,107,108,109,110],
    'Product_Category':['Electronics','Clothing', 'Electronics', 'Furniture',
    'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region':['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
            'South', 'North'],
    'Amount':[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

In [24]:
print(transactions)

   Transaction_ID Product_Category Region  Amount
0             101      Electronics  North     200
1             102         Clothing  South     150
2             103      Electronics  North     300
3             104        Furniture   East     450
4             105         Clothing   West     200
5             106      Electronics  North     250
6             107        Furniture   East     300
7             108         Clothing   West     180
8             109        Furniture  South     350
9             110      Electronics  North     400


In [26]:
print(transactions.head())
print(transactions.tail())
print(transactions.shape)
print(transactions.dtypes)
print(transactions.columns)


   Transaction_ID Product_Category Region  Amount
0             101      Electronics  North     200
1             102         Clothing  South     150
2             103      Electronics  North     300
3             104        Furniture   East     450
4             105         Clothing   West     200
   Transaction_ID Product_Category Region  Amount
5             106      Electronics  North     250
6             107        Furniture   East     300
7             108         Clothing   West     180
8             109        Furniture  South     350
9             110      Electronics  North     400
(10, 4)
Transaction_ID      int64
Product_Category      str
Region                str
Amount              int64
dtype: object
Index(['Transaction_ID', 'Product_Category', 'Region', 'Amount'], dtype='str')


In [27]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    10 non-null     int64
 1   Product_Category  10 non-null     str  
 2   Region            10 non-null     str  
 3   Amount            10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 593.0 bytes


In [28]:
print(transactions[['Product_Category','Amount']])

  Product_Category  Amount
0      Electronics     200
1         Clothing     150
2      Electronics     300
3        Furniture     450
4         Clothing     200
5      Electronics     250
6        Furniture     300
7         Clothing     180
8        Furniture     350
9      Electronics     400


In [60]:
print(transactions.iloc[:,-3:])

  Region  Amount  Discount
0  North     200      20.0
1  South     165      16.5
2  North     300      30.0
3   East     450      45.0
4   West     200      20.0
5  North     250      25.0
6   East     300      30.0
7   West     180      18.0
9  North     400      40.0


In [61]:
print(transactions[(transactions['Region']=='North') &
     (transactions['Amount']>200)])

   Transaction_ID Product_Category Region  Amount  Discount
2             103      Electronics  North     300      30.0
5             106      Electronics  North     250      25.0
9             110      Electronics  North     400      40.0


In [62]:
print(transactions['Product_Category'].value_counts())

Product_Category
Electronics    4
Clothing       3
Furniture      2
Name: count, dtype: int64


In [63]:
print(transactions['Region'].unique())

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str


In [64]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    165.0
West     190.0
Name: Amount, dtype: float64


In [65]:
transactions.loc[transactions['Transaction_ID']==102, 'Amount']= 165

In [66]:
print(transactions)

   Transaction_ID Product_Category Region  Amount  Discount
0             101      Electronics  North     200      20.0
1             102         Clothing  South     165      16.5
2             103      Electronics  North     300      30.0
3             104        Furniture   East     450      45.0
4             105         Clothing   West     200      20.0
5             106      Electronics  North     250      25.0
6             107        Furniture   East     300      30.0
7             108         Clothing   West     180      18.0
9             110      Electronics  North     400      40.0


In [67]:
transactions['Discount']= transactions['Amount']*10/100

In [68]:
print(transactions)

   Transaction_ID Product_Category Region  Amount  Discount
0             101      Electronics  North     200      20.0
1             102         Clothing  South     165      16.5
2             103      Electronics  North     300      30.0
3             104        Furniture   East     450      45.0
4             105         Clothing   West     200      20.0
5             106      Electronics  North     250      25.0
6             107        Furniture   East     300      30.0
7             108         Clothing   West     180      18.0
9             110      Electronics  North     400      40.0


In [69]:
transactions=transactions.drop(8)
print(transactions)

KeyError: '[8] not found in axis'

In [70]:
transactions=transactions.drop(columns='Discount')

In [71]:
print(transactions)

   Transaction_ID Product_Category Region  Amount
0             101      Electronics  North     200
1             102         Clothing  South     165
2             103      Electronics  North     300
3             104        Furniture   East     450
4             105         Clothing   West     200
5             106      Electronics  North     250
6             107        Furniture   East     300
7             108         Clothing   West     180
9             110      Electronics  North     400
